import { Song, Setlist, User, AudioTrack, SectionMarker, ChordData } from '../types';

// Generate mock waveform data
const generateWaveform = (samples: number = 200): number[] => {
  return Array.from({ length: samples }, () => Math.random() * 0.8 + 0.1);
};

// Mock audio tracks
const createMockTracks = (): AudioTrack[] => [
  {
    id: 'track-1',
    name: 'Drums',
    type: 'drums',
    volume: 1.0, // 0dB
    muted: false,
    solo: false,
    waveformData: generateWaveform(),
    output: 1,
    color: '#60a5fa',
  },
  {
    id: 'track-2',
    name: 'Bass',
    type: 'bass',
    volume: 0.89, // -1dB
    muted: false,
    solo: false,
    waveformData: generateWaveform(),
    output: 1,
    color: '#ef4444',
  },
  {
    id: 'track-3',
    name: 'Electric Guitar',
    type: 'guitar',
    volume: 0.79, // -2dB
    muted: false,
    solo: false,
    waveformData: generateWaveform(),
    output: 1,
    color: '#22c55e',
  },
  {
    id: 'track-4',
    name: 'Keys',
    type: 'keys',
    volume: 0.71, // -3dB
    muted: false,
    solo: false,
    waveformData: generateWaveform(),
    output: 1,
    color: '#f59e0b',
  },
  {
    id: 'track-5',
    name: 'Lead Vocals',
    type: 'vocals',
    volume: 1.12, // +1dB
    muted: false,
    solo: false,
    waveformData: generateWaveform(),
    output: 1,
    color: '#a855f7',
  },
  {
    id: 'track-6',
    name: 'Backing Vocals',
    type: 'vocals',
    volume: 0.63, // -4dB
    muted: false,
    solo: false,
    waveformData: generateWaveform(),
    output: 1,
    color: '#ec4899',
  },
  {
    id: 'track-7',
    name: 'Click Track',
    type: 'click',
    volume: 0.56, // -5dB
    muted: false,
    solo: false,
    waveformData: generateWaveform(200),
    output: 2, // Separate output for drummer
    color: '#14b8a6',
  },
  {
    id: 'track-8',
    name: 'Guide Cue',
    type: 'guide',
    volume: 0.79, // -2dB
    muted: false,
    solo: false,
    waveformData: generateWaveform(),
    output: 2,
    color: '#f97316',
  },
];

// Mock section markers
const createMockMarkers = (): SectionMarker[] => [
  { id: 'm1', time: 0, label: 'Intro', type: 'intro' },
  { id: 'm2', time: 15, label: 'Verse 1', type: 'verse' },
  { id: 'm3', time: 45, label: 'Chorus', type: 'chorus' },
  { id: 'm4', time: 75, label: 'Verse 2', type: 'verse' },
  { id: 'm5', time: 105, label: 'Chorus', type: 'chorus' },
  { id: 'm6', time: 135, label: 'Bridge', type: 'bridge' },
  { id: 'm7', time: 165, label: 'Chorus', type: 'chorus' },
  { id: 'm8', time: 195, label: 'Outro', type: 'outro' },
];

// Mock chord data
const createMockChords = (): ChordData[] => [
  { time: 0, chord: 'C', duration: 4 },
  { time: 4, chord: 'G', duration: 4 },
  { time: 8, chord: 'Am', duration: 4 },
  { time: 12, chord: 'F', duration: 4 },
  { time: 15, chord: 'C', duration: 4 },
  { time: 19, chord: 'G', duration: 4 },
  { time: 23, chord: 'Am', duration: 4 },
  { time: 27, chord: 'F', duration: 4 },
  { time: 45, chord: 'F', duration: 4 },
  { time: 49, chord: 'C', duration: 4 },
  { time: 53, chord: 'G', duration: 4 },
  { time: 57, chord: 'Am', duration: 4 },
];

// Mock chord markers for performance mode
const createMockChordMarkers = () => [
  { time: 0, chord: 'C' },
  { time: 4, chord: 'G' },
  { time: 8, chord: 'Am' },
  { time: 12, chord: 'F' },
  { time: 15, chord: 'C' },
  { time: 19, chord: 'G' },
  { time: 23, chord: 'Am' },
  { time: 27, chord: 'F' },
  { time: 31, chord: 'C' },
  { time: 35, chord: 'G/B' },
  { time: 39, chord: 'Am7' },
  { time: 43, chord: 'F' },
  { time: 45, chord: 'F' },
  { time: 49, chord: 'C' },
  { time: 53, chord: 'G' },
  { time: 57, chord: 'Am' },
  { time: 61, chord: 'F' },
  { time: 65, chord: 'C/E' },
  { time: 69, chord: 'G' },
  { time: 73, chord: 'Am7' },
  { time: 75, chord: 'C' },
  { time: 79, chord: 'G' },
  { time: 83, chord: 'Am' },
  { time: 87, chord: 'F' },
  { time: 91, chord: 'C' },
  { time: 95, chord: 'G/B' },
  { time: 99, chord: 'Am7' },
  { time: 103, chord: 'F' },
  { time: 105, chord: 'F' },
  { time: 109, chord: 'C' },
  { time: 113, chord: 'G' },
  { time: 117, chord: 'Am' },
  { time: 121, chord: 'F' },
  { time: 125, chord: 'C/E' },
  { time: 129, chord: 'G' },
  { time: 133, chord: 'Am7' },
  { time: 135, chord: 'Dm7' },
  { time: 139, chord: 'Am' },
  { time: 143, chord: 'G' },
  { time: 147, chord: 'F' },
  { time: 151, chord: 'C/E' },
  { time: 155, chord: 'Dm7' },
  { time: 159, chord: 'G' },
  { time: 163, chord: 'Gsus4' },
  { time: 165, chord: 'F' },
  { time: 169, chord: 'C' },
  { time: 173, chord: 'G' },
  { time: 177, chord: 'Am' },
  { time: 181, chord: 'F' },
  { time: 185, chord: 'C/E' },
  { time: 189, chord: 'G' },
  { time: 193, chord: 'Am7' },
  { time: 195, chord: 'F' },
  { time: 199, chord: 'C' },
  { time: 203, chord: 'G' },
  { time: 207, chord: 'Am' },
  { time: 211, chord: 'F' },
  { time: 215, chord: 'C/E' },
  { time: 219, chord: 'G' },
  { time: 223, chord: 'C' },
];

// Mock songs
export const mockSongs: Song[] = [
  {
    id: 'song-1',
    title: 'Amazing Grace',
    artist: 'Traditional',
    key: 'C',
    tempo: 120,
    duration: 225,
    tracks: createMockTracks(),
    markers: createMockMarkers(),
    chords: createMockChords(),
    chordMarkers: createMockChordMarkers(),
    loops: [
      { id: 'loop-1', name: 'Chorus Loop', startTime: 45, endTime: 75 },
    ],
    mixPresets: [
      {
        id: 'preset-1',
        name: 'My Practice Mix',
        tracks: [
          { trackId: 'track-1', volume: 0.5, muted: false },
          { trackId: 'track-5', volume: 0.3, muted: false },
          { trackId: 'track-7', volume: 0.8, muted: false },
        ],
      },
    ],
    notes: [
      {
        id: 'note-1',
        userId: 'user-1',
        content: 'Watch for the key change in the bridge',
        time: 135,
        isPrivate: false,
      },
    ],
    thumbnailUrl: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400',
    version: 1,
    lastModified: new Date('2025-10-20'),
    createdBy: 'admin-1',
    tags: ['worship', 'traditional'],
    source: 'imported',
  },
  {
    id: 'song-2',
    title: 'How Great Is Our God',
    artist: 'Chris Tomlin',
    key: 'G',
    tempo: 76,
    duration: 240,
    tracks: createMockTracks(),
    markers: createMockMarkers(),
    chords: createMockChords(),
    chordMarkers: createMockChordMarkers(),
    loops: [],
    mixPresets: [],
    notes: [],
    thumbnailUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400',
    version: 2,
    lastModified: new Date('2025-10-22'),
    createdBy: 'admin-1',
    tags: ['worship', 'contemporary'],
    source: 'imported',
  },
  {
    id: 'song-3',
    title: 'Oceans',
    artist: 'Hillsong United',
    key: 'D',
    tempo: 72,
    duration: 510,
    tracks: createMockTracks(),
    markers: createMockMarkers(),
    chords: createMockChords(),
    chordMarkers: createMockChordMarkers(),
    loops: [],
    mixPresets: [],
    notes: [],
    thumbnailUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400',
    version: 1,
    lastModified: new Date('2025-10-15'),
    createdBy: 'user-2',
    tags: ['worship', 'ballad'],
    source: 'imported',
  },
  {
    id: 'song-4',
    title: 'Reckless Love',
    artist: 'Cory Asbury',
    key: 'E',
    tempo: 130,
    duration: 320,
    tracks: createMockTracks(),
    markers: createMockMarkers(),
    chords: createMockChords(),
    chordMarkers: createMockChordMarkers(),
    loops: [],
    mixPresets: [],
    notes: [],
    thumbnailUrl: 'https://images.unsplash.com/photo-1460667262436-cf19894f4774?w=400',
    version: 1,
    lastModified: new Date('2025-10-18'),
    createdBy: 'user-2',
    tags: ['worship', 'upbeat'],
    source: 'imported',
  },
  {
    id: 'song-5',
    title: 'Goodness of God',
    artist: 'Bethel Music',
    key: 'C',
    tempo: 123,
    duration: 378,
    tracks: createMockTracks(),
    markers: createMockMarkers(),
    chords: createMockChords(),
    chordMarkers: createMockChordMarkers(),
    loops: [],
    mixPresets: [],
    notes: [],
    thumbnailUrl: 'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=400',
    version: 1,
    lastModified: new Date('2025-10-10'),
    createdBy: 'admin-1',
    tags: ['worship', 'contemporary'],
    source: 'imported',
  },
];

// Mock setlists
export const mockSetlists: Setlist[] = [
  {
    id: 'setlist-1',
    name: 'Sunday Service - Oct 27',
    songIds: ['song-1', 'song-2', 'song-5'],
    createdBy: 'admin-1',
    sharedWith: ['user-1', 'user-2'],
    eventDate: new Date('2025-10-27'),
    notes: 'Remember to mute guide track for live performance',
  },
  {
    id: 'setlist-2',
    name: 'Wednesday Night Worship',
    songIds: ['song-3', 'song-4'],
    createdBy: 'user-2',
    sharedWith: ['user-1'],
    eventDate: new Date('2025-10-30'),
  },
  {
    id: 'setlist-3',
    name: 'Practice Session',
    songIds: ['song-1', 'song-3', 'song-4', 'song-5'],
    createdBy: 'user-1',
    sharedWith: [],
  },
];

// Mock users
export const mockUsers: User[] = [
  {
    id: 'user-1',
    name: 'John Musician',
    email: 'john@example.com',
    role: 'musician',
    preferences: {
      defaultOutput: 1,
      performanceMode: false,
    },
  },
  {
    id: 'user-2',
    name: 'Sarah Leader',
    email: 'sarah@example.com',
    role: 'leader',
    preferences: {
      defaultOutput: 1,
      performanceMode: true,
    },
  },
  {
    id: 'admin-1',
    name: 'Admin User',
    email: 'admin@example.com',
    role: 'admin',
    preferences: {
      defaultOutput: 1,
      performanceMode: false,
    },
  },
];

export const currentUser = mockUsers[0];
